[![Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://www.kaggle.com/code/maryrobynbernabe/coral-sound-project-2-dataset-splitting)

In [1]:
# define the paths
MAIN_CSV = "/kaggle/input/notebooks/maryrobynbernabe/coral-sound-project-1-data-processing/featurizedaudio.csv"

In [2]:
import pandas as pd

# load the main csv
df_main = pd.read_csv(MAIN_CSV)
df_main.head()

,audio_file_name,RMSE,SPECTRAL_CENTROID,SPECTRAL_BANDWIDTH,ROLLOFF,ZERO_CROSSING_RATE,MFCC_FEATURE_0,MFCC_FEATURE_1,MFCC_FEATURE_2,MFCC_FEATURE_3,...,MFCC_FEATURE_11,MFCC_FEATURE_12,MFCC_FEATURE_13,MFCC_FEATURE_14,MFCC_FEATURE_15,MFCC_FEATURE_16,MFCC_FEATURE_17,MFCC_FEATURE_18,MFCC_FEATURE_19,labels
0,BoN10.2359R.1677983769.180905.1.12.wav,0.011000,3974.266047,3494.028931,8364.436921,0.003938,-508.00090,-70.216250,-5.753670,16.357086,...,13.664226,8.291626,11.360783,3.441027,8.500538,4.896815,8.645019,4.216819,10.106939,Restored
1,BoN11.0529R.1677983769.180906.4.45.wav,0.010963,3616.489840,3552.171710,8205.517049,0.002235,-527.85390,-55.517910,11.541430,25.993612,...,8.502945,5.018967,8.891335,3.383256,8.611948,5.192332,8.339452,3.200580,8.528194,Restored
2,BoN11.1103D.1678278701.180906.4.32.wav,0.013505,2203.188939,3327.939877,6814.896291,0.000203,-596.17380,-30.206333,32.680866,24.321074,...,7.948227,3.422245,8.702552,2.499417,7.926837,3.409961,7.515243,3.444732,6.654954,Degraded
3,BaN12.0529R.1677983769.180907.5.46.wav,0.010878,2849.557129,3414.181023,7438.905018,0.000900,-547.84480,-25.308653,21.758960,28.064041,...,6.696609,3.105051,8.415883,3.191075,9.433007,4.989413,8.680643,3.263001,7.559287,Restored
4,BaF5.1732R.1678278701.180831.2.12.wav,0.013718,2819.472916,3277.748076,7121.031940,0.001491,-505.59583,-27.010841,5.536732,34.013490,...,8.420740,4.733733,11.414305,4.753037,11.750537,7.183123,10.483688,6.316996,10.076572,Restored

In [3]:
LABEL_COLUMN = 'labels'

In [4]:
# Check the distribution of unique elements in Label  Column
print(df_main[LABEL_COLUMN].value_counts())

labels
Restored    110
Healthy      81
Degraded     71
Name: count, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

# Split the main dataframe to train and test
df_train, df_test = train_test_split(df_main, test_size = 0.2, stratify=df_main[LABEL_COLUMN],random_state=42)

In [6]:
# Reset the indexes
df_train.reset_index(drop=True)

,audio_file_name,RMSE,SPECTRAL_CENTROID,SPECTRAL_BANDWIDTH,ROLLOFF,ZERO_CROSSING_RATE,MFCC_FEATURE_0,MFCC_FEATURE_1,MFCC_FEATURE_2,MFCC_FEATURE_3,...,MFCC_FEATURE_11,MFCC_FEATURE_12,MFCC_FEATURE_13,MFCC_FEATURE_14,MFCC_FEATURE_15,MFCC_FEATURE_16,MFCC_FEATURE_17,MFCC_FEATURE_18,MFCC_FEATURE_19,labels
0,BoN11.0529H.1678278701.180906.4.28.wav,0.013586,3281.713706,3527.383649,7962.826850,0.001039,-495.97717,-25.360006,15.571173,10.742051,...,8.197722,2.783091,7.597062,1.207888,7.518812,4.713681,7.761002,2.533650,7.588442,Healthy
1,BaF5.1330H.671907872.180831.3.18.wav,0.000624,5506.005847,3041.157454,8939.850109,0.254344,-611.53705,-16.766792,34.535435,31.588339,...,2.514375,-3.736288,2.271210,-1.622616,3.087977,-2.768877,3.200042,-0.567399,1.135935,Healthy
2,SaF5.1125R.1678278701.180831.5.33.wav,0.013555,2238.091512,3304.071066,6828.200377,0.000297,-581.68410,-27.747358,29.402313,28.410930,...,6.210212,3.216774,8.026078,1.109000,7.852259,3.715654,7.919775,3.877651,7.079189,Restored
3,SaF2.1112R.671907872.180828.5.49.wav,0.000631,5802.834647,2953.160951,9101.115800,0.419278,-584.80005,-26.345171,26.770414,24.583618,...,6.878403,0.387064,2.824635,-1.029802,4.852212,-1.872255,3.994614,0.126457,2.576796,Restored
4,SaF5.1202D.1677983769.180831.5.30.wav,0.010829,2637.516704,3333.849107,7146.860951,0.000484,-559.42035,-37.722710,3.701616,32.711998,...,6.353807,3.654529,7.881154,1.278509,7.627464,5.473676,8.769265,4.218484,9.438093,Degraded
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,SaF3.1355D.805322778.180829.3.25.wav,0.010846,2758.027275,3443.808429,7479.717271,0.000336,-566.64746,-44.215565,6.140578,26.906970,...,6.266344,-1.134672,6.450532,6.044149,7.255554,2.443519,9.685577,4.403631,7.238421,Degraded
205,BoF4.1733R.805322778.180830.2.10.wav,0.010876,3005.406209,3506.652216,7754.886441,0.001176,-561.15350,-39.594822,19.456627,22.307707,...,9.206425,0.709136,6.028572,7.086573,9.402752,3.269751,10.147239,4.763659,6.565988,Restored
206,BoF4.1300R.805322778.180830.2.26.wav,0.010849,2393.969996,3324.099784,6882.041719,0.000574,-607.89130,-39.080997,26.009440,29.577496,...,11.116720,2.540149,7.342004,7.722256,8.775329,2.507036,10.128836,5.464726,7.338312,Restored
207,BaN12.0529R.1677983769.180907.1.6.wav,0.010970,3804.640391,3494.798013,8237.408523,0.002985,-495.37772,-45.217087,10.058172,28.671942,...,5.885247,1.047536,5.448494,-0.104444,6.363506,3.115238,8.144170,2.930906,7.567463,Restored
208,BoN10.1731R.1677983769.180905.4.42.wav,0.010961,3813.445187,3538.885656,8327.887142,0.003165,-505.42444,-50.603830,6.726087,16.310665,...,9.446142,4.837527,9.283340,2.495734,6.960176,4.275660,8.746872,4.770905,10.188201,Restored

In [7]:
# Check the distribution of unique elements in Label  Column
print(df_train[LABEL_COLUMN].value_counts())

labels
Restored    88
Healthy     64
Degraded    57
Name: count, dtype: int64

In [8]:
df_test.reset_index(drop=True)

,audio_file_name,RMSE,SPECTRAL_CENTROID,SPECTRAL_BANDWIDTH,ROLLOFF,ZERO_CROSSING_RATE,MFCC_FEATURE_0,MFCC_FEATURE_1,MFCC_FEATURE_2,MFCC_FEATURE_3,...,MFCC_FEATURE_11,MFCC_FEATURE_12,MFCC_FEATURE_13,MFCC_FEATURE_14,MFCC_FEATURE_15,MFCC_FEATURE_16,MFCC_FEATURE_17,MFCC_FEATURE_18,MFCC_FEATURE_19,labels
0,BoF3.1205H.1678278701.180829.3.30.wav,0.013509,2371.907343,3346.767120,6973.074501,0.000383,-581.47125,-31.149992,31.942299,25.752459,...,7.486877,4.100320,9.267488,4.850466,10.294695,5.458443,9.026334,4.239098,8.640108,Healthy
1,BoF5.0532D.671907872.180831.3.14.wav,0.000865,6161.231539,2825.887582,9247.689914,0.452658,-572.35670,-42.258537,24.068690,18.263010,...,6.299976,0.018795,4.825120,1.052692,6.586744,-0.410561,5.983515,0.842368,2.919782,Degraded
2,BaN12.0915H.805322778.180907.5.59.wav,0.010927,3035.079825,3355.987134,7441.117505,0.001610,-533.98660,-40.026726,1.502462,27.008759,...,11.493428,3.216962,9.309798,9.065527,10.811224,5.195178,12.704576,7.134038,8.885212,Healthy
3,BoF4.2333R.805322778.180830.2.6.wav,0.010955,3606.676635,3525.684684,8136.329967,0.002737,-546.04486,-73.790490,2.513496,25.006584,...,13.005180,4.703271,9.324385,7.987784,9.296119,3.120103,10.756012,6.079686,7.576439,Restored
4,BoN11.1103R.1677983769.180906.3.34.wav,0.010840,2845.637586,3484.363955,7609.820651,0.000821,-573.16070,-36.600240,26.502802,21.257563,...,7.846145,4.681725,7.935759,3.057675,9.470773,5.528121,8.262956,2.826576,8.037794,Restored
5,BoN10.2359H.1678278701.180905.4.54.wav,0.013594,3425.095702,3533.205967,8047.434672,0.001405,-529.00480,-67.102480,4.083846,25.489748,...,11.232746,6.095686,10.505655,2.582521,8.243756,5.901369,9.631198,4.778630,9.487319,Healthy
6,BaN11.2330H.805322778.180906.4.46.wav,0.011135,3970.654863,3376.244337,8153.834028,0.004814,-493.37335,-77.272240,-23.928200,17.560910,...,12.963978,4.464390,9.325088,8.380471,10.278222,5.097357,12.948753,8.395458,10.270882,Healthy
7,BaN11.2330H.805322778.180906.5.50.wav,0.011096,3967.303172,3383.279492,8143.759089,0.004536,-501.65558,-82.324900,-23.988210,19.536455,...,11.930386,3.588416,9.149800,8.492353,10.878129,5.025447,13.156095,8.113721,9.780655,Healthy
8,SaF4.0902R.805322778.180830.3.31.wav,0.010888,3113.296387,3497.053347,7785.286257,0.001198,-549.88470,-40.999294,20.612453,29.007710,...,8.881417,0.887103,6.802789,5.814897,8.264313,2.927873,10.472735,4.579809,6.049173,Restored
9,SaF1.1733R.805322778.180827.4.45.wav,0.010951,3702.172538,3614.286517,8369.782722,0.001841,-504.40286,-33.585430,17.094430,12.966355,...,12.369679,1.033730,7.315499,3.300840,2.255948,0.249985,8.452398,2.855408,7.111711,Restored
10,SaF2.1112D.1678278701.180828.3.16.wav,0.013513,2288.368155,3246.245976,6701.942808,0.000169,-558.32150,-28.778435,11.096742,32.568203,...,5.207071,2.843910,8.624826,1.705241,7.404059,4.340198,7.362153,2.512309,8.462722,Degraded
11,BoF5.0940D.1677983769.180831.1.1.wav,0.010832,2535.613510,3476.228702,7447.525799,0.000320,-600.87616,-34.601276,35.214233,23.099949,...,8.701986,4.825220,9.688808,4.459845,9.504640,6.772559,9.605337,4.928415,9.471116,Degraded
12,BaF5.1330R.1678278701.180831.2.13.wav,0.013536,2122.543890,3050.050228,5857.531247,0.000625,-586.44670,-37.649870,11.445387,38.911327,...,8.829560,5.665588,12.007286,5.822764,12.646526,7.233295,10.994810,7.033155,9.958290,Restored
13,BoF4.2333H.1677983769.180830.5.54.wav,0.010925,3631.603822,3546.722740,8187.771323,0.002123,-541.68414,-68.874940,8.259998,26.828300,...,10.477839,5.985028,10.119428,4.497376,8.622128,5.025981,8.720577,3.447440,7.694546,Healthy
14,SaF5.1202R.1678278701.180831.5.27.wav,0.013517,2222.689282,3306.830884,6822.833743,0.000216,-582.44080,-26.137728,29.410488,26.774666,...,7.318430,4.221853,7.791697,1.752331,8.557426,3.481869,7.482505,4.433017,7.527123,Restored
15,BaF3.0915H.1678278701.180829.4.52.wav,0.013523,1891.777571,3016.899630,5395.304875,0.000333,-581.09850,-0.133614,37.255867,32.281406,...,4.131716,0.744574,7.294945,0.829881,6.395241,2.968916,6.366645,1.108863,4.540984,Healthy
16,BoN10.2359H.1678278701.180905.2.46.wav,0.013575,3356.047713,3534.462578,8011.130724,0.001168,-530.57360,-64.828960,3.237101,23.319520,...,12.721142,7.415269,11.195780,3.142526,8.607796,6.020940,9.688036,4.853985,9.663209,Healthy
17,BaF3.0533H.1677983769.180829.5.59.wav,0.010876,2844.460255,3369.244449,7323.334883,0.001157,-536.42505,-14.918222,29.577496,35.013157,...,8.847975,3.571419,8.726528,5.806723,11.948134,6.563458,9.203614,4.253393,8.155862,Healthy
18,BaF2.2333H.1677983769.180828.5.51.wav,0.010941,3411.988704,3453.090683,7884.573156,0.002338,-534.26490,-55.028843,7.053959,30.778362,...,7.452315,1.526111,6.458186,2.707225,9.087985,5.263914,9.057238,4.075698,8.555535,Healthy
19,BaN12.0529R.1677983769.180907.5.46.wav,0.010878,2849.557129,3414.181023,7438.905018,0.000900,-547.84480,-25.308653,21.758960,28.064041,...,6.696609,3.105051,8.415883,3.191075,9.433007,4.989413,8.680643,3.263001,7.559287,Restored
20,BoN11.1200H.805322778.180906.3.12.wav,0.010856,2567.306053,3347.004394,7097.844580,0.000833,-591.26337,-38.742302,22.370838,25.578653,...,11.269768,2.944656,7.295117,6.633422,8.677464,3.432313,10.487514,4.454651,5.748975,Healthy
21,BoF5.0940R.1678278701.180831.1.7.wav,0.013543,2459.479191,3277.100827,6811.100481,0.000740,-569.95105,-40.279000,14.547183,28.770336,...,9.015844,4.132117,10.405693,5.294893,10.771597,6.626439,10.028225,4.849431,9.028384,Restored
22,BoF3.1205R.1677983769.180829.5.58.wav,0.010848,2549.663524,3392.005187,7223.472987,0.000690,-591.17926,-33.789540,26.881075,24.564160,...,8.059512,5.209289,9.171925,4.248157,11.398563,8.035179,10.810411,6.687450,11.155964,Restored
23,SaF1.1733D.1677983769.180827.1.12.wav,0.010908,3393.038001,3460.096425,7921.585433,0.001748,-512.34460,-43.485430,-1.091493,24.504135,...,7.709975,3.401813,8.495861,2.214075,8.401701,4.647284,7.032438,2.227696,8.042659,Degraded
24,BoN10.2359R.1677983769.180905.1.12.wav,0.011000,3974.266047,3494.028931,8364.436921,0.003938,-508.00090,-70.216250,-5.753670,16.357086,...,13.664226,8.291626,11.360783,3.441027,8.500538,4.896815,8.645019,4.216819,10.106939,Restored
25,SaF1.1733D.1677983769.180827.2.16.wav,0.010947,3407.933250,3447.925056,7900.623059,0.001839,-514.27155,-50.169666,-8.429587,19.246206,...,6.751307,3.990218,8.714898,2.598654,8.701884,6.019214,8.511042,3.409992,10.117222,Degraded
26,BoN11.0529R.1677983769.180906.5.57.wav,0.010931,3493.623859,3517.685615,8073.309515,0.002046,-532.66520,-54.884663,10.049715,27.669432,...,9.630569,5.918955,10.340454,3.647616,9.197850,5.733306,8.613919,3.322120,8.324392,Restored
27,SaF3.1733D.805322778.180829.2.26.wav,0.010971,3694.760723,3458.588258,8130.050839,0.002683,-492.10556,-51.360302,-12.871944,14.591585,...,9.725270,1.032082,7.817919,6.670582,7.958121,3.208792,10.584025,4.874713,7.549222,Degraded
28,SaF2.0534D.1677983769.180828.3.26.wav,0.011144,3983.938899,3322.971703,8108.755134,0.005352,-463.54248,-61.310640,-26.872236,12.281204,...,7.759409,3.815933,7.919147,2.808383,8.790941,5.165182,8.173972,4.497430,9.737377,Degraded
29,SaF3.1733D.805322778.180829.1.17.wav,0.010942,3472.405817,3460.676995,7980.685075,0.002025,-508.30728,-48.783400,-8.298450,17.899223,...,9.190306,1.382953,8.188383,6.993757,8.308243,3.323366,10.967513,5.059970,7.955177,Degraded
30,BaN10.0927R.1678278701.180905.5.56.wav,0.013614,2499.375827,3150.614237,6541.543778,0.001070,-531.09470,-27.409101,2.326592,32.314300,...,8.295600,4.559841,11.459229,5.694962,12.384800,7.950407,11.697948,7.360977,10.545229,Restored
31,BaF3.0915R.1677983769.180829.5.56.wav,0.010931,2819.829326,3278.991117,7111.057000,0.001425,-535.21954,-26.114758,9.229005,31.496058,...,5.912678,2.584289,7.291861,2.972063,9.448821,5.850547,8.688558,4.792155,9.362325,Restored
32,SaF2.1112D.1678278701.180828.4.33.wav,0.013522,2251.639090,3237.088110,6652.247275,0.000186,-567.60547,-33.941520,11.040202,34.038670,...,4.801831,2.558449,7.888170,1.366469,8.912494,4.983642,6.904267,3.823250,9.503981,Degraded
33,BoN12.1220R.1677983769.180907.1.10.wav,0.010850,2872.794167,3513.888332,7707.874225,0.000867,-572.63420,-36.424114,26.480290,19.909225,...,7.371226,5.145086,9.785918,4.586571,10.017008,5.910436,9.108637,4.019580,8.814730,Restored
34,BaF2.1733R.671907872.180828.3.30.wav,0.001754,5308.894854,2811.264213,8652.622679,0.355408,-492.69660,-35.502594,-3.666287,25.237202,...,5.576926,-0.521953,5.168603,1.871410,7.198234,0.657522,6.605339,2.789604,5.418714,Restored
35,BoN10.1731R.1677983769.180905.2.20.wav,0.010913,3289.655488,3515.316755,7952.314413,0.001766,-545.24536,-45.908400,21.016410,29.106146,...,6.919571,3.131537,8.294746,2.811148,8.367405,5.506005,9.070333,4.350741,9.311477,Restored
36,BoF5.0532R.805322778.180831.1.2.wav,0.011010,3867.293537,3491.357662,8257.733400,0.003517,-503.18112,-57.237050,1.145046,21.181389,...,10.543054,1.394291,5.897697,4.745406,6.758682,1.483541,9.504272,4.918718,7.253713,Restored
37,BoF4.1300D.671907872.180830.2.29.wav,0.000558,6037.183802,3050.388105,9308.552046,0.356459,-614.17224,-19.639084,41.516563,15.007198,...,5.120440,-0.436511,4.610014,0.417361,5.695415,-0.391055,5.687209,0.314123,1.274146,Degraded
38,SaF4.0902R.805322778.180830.1.2.wav,0.010858,2973.220096,3514.724153,7751.698960,0.000730,-560.07556,-40.311623,21.051851,28.464075,...,8.698771,0.170360,5.792203,4.265963,6.752161,1.116469,8.998872,3.999565,5.819563,Restored
39,BaN11.1731H.805322778.180906.2.17.wav,0.010977,3758.832011,3637.887891,8433.990667,0.001952,-518.49457,-44.998024,19.681026,20.699099,...,10.766698,1.564179,6.610844,5.275942,5.556129,0.475218,8.497247,2.841884,5.814605,Healthy
40,BoF1.1328H.1678278701.180827.4.28.wav,0.013525,2365.535682,3328.942719,6903.283257,0.000425,-569.94476,-19.963284,35.091053,25.205870,...,10.321053,5.500223,10.535923,5.113524,10.020454,4.992189,7.950960,3.205890,6.751132,Healthy
41,BoN11.1103R.1677983769.180906.2.20.wav,0.010837,2883.368039,3483.999737,7637.174652,0.000872,-572.02640,-39.823190,24.798320,25.169224,...,9.841387,4.635553,7.916320,2.798582,9.499604,6.325325,8.815740,3.711778,8.288709,Restored
42,BaN11.1315H.805322778.180906.4.38.wav,0.010880,3341.643028,3616.434793,8164.217299,0.001152,-561.85860,-60.080060,11.636697,19.740921,...,13.929027,4.529800,9.546779,7.022059,7.060364,1.623817,9.404253,3.396704,6.059956,Healthy
43,SaF5.1202D.1677983769.180831.3.24.wav,0.010834,2659.585752,3347.431175,7196.748149,0.000541,-558.29560,-35.850906,7.083685,33.792520,...,6.683310,4.177402,7.853956,1.329454,8.307273,5.457411,7.959053,4.135650,9.259513,Degraded
44,SaF3.1733R.1677983769.180829.3.23.wav,0.010929,3611.551155,3593.861840,8265.279188,0.001526,-531.05380,-53.339016,14.378963,24.178726,...,9.558161,5.200023,8.607759,2.841103,7.819667,4.289100,7.482529,4.080815,8.838831,Restored
45,BaF3.0915H.1678278701.180829.1.20.wav,0.013519,2045.908017,3107.362537,5923.855846,0.000359,-579.42510,-11.419057,32.961308,32.236160,...,4.145525,1.582375,8.346098,2.435157,8.445658,5.232410,8.744172,3.441431,6.574375,Healthy
46,BaN10.0927H.1677983769.180905.2.12.wav,0.010854,2719.390142,3319.214100,7106.482028,0.001047,-552.61456,-21.580782,23.363367,32.411026,...,7.465345,1.279480,6.240872,2.984309,9.378074,5.189072,8.456563,3.329365,7.381864,Healthy
47,SaN11.0940D.1678278701.180906.4.40.wav,0.013540,2708.751425,3295.336142,7085.844653,0.000797,-526.88380,-36.713220,-4.409191,20.730476,...,5.832080,2.132418,8.772303,1.948879,8.133164,4.119278,8.796148,4.852749,8.345887,Degraded
48,BoF4.2333R.805322778.180830.1.2.wav,0.010903,3437.174212,3545.620296,8067.438717,0.001959,-552.40894,-65.948044,6.740626,24.877270,...,12.602589,3.631912,8.313820,7.696442,9.312541,3.149097,10.604530,6.158724,7.774970,Restored
49,SaF3.2333D.805322778.180829.2.34.wav,0.011020,3677.591019,3414.844879,8023.813981,0.003287,-503.65094,-65.984010,-23.684843,10.427032,...,11.671873,2.781128,9.189248,7.439147,8.537909,3.591084,10.720584,5.477087,8.682095,Degraded
50,SaF2.0534D.1677983769.180828.2.21.wav,0.011226,4065.248257,3306.155213,8141.925767,0.005969,-456.86774,-63.566788,-29.136415,11.441834,...,7.817728,3.938753,7.722735,2.879529,8.175339,4.392483,7.556086,3.557775,8.834278,Degraded
51,BaF4.1040R.805322778.180830.3.37.wav,0.010909,2609.026790,3215.770062,6784.238143,0.001282,-553.13970,-26.380136,9.524192,31.804707,...,7.463203,1.652016,6.980092,7.269810,10.151894,3.841588,10.530134,6.896518,8.435343,Restored
52,BaN11.1315H.805322778.180906.5.55.wav,0.010879,3306.517336,3620.276836,8156.334013,0.001085,-552.47864,-45.935604,23.014965,27.684937,...,14.498225,5.123799,10.117650,7.976618,7.681532,2.006120,9.299381,2.989855,5.674894,Healthy

In [9]:
# Check the distribution of unique elements in Label  Columnp
print(df_test[LABEL_COLUMN].value_counts())

labels
Restored    22
Healthy     17
Degraded    14
Name: count, dtype: int64

In [10]:
# Save train and test sets to CSV files
df_train.to_csv('/kaggle/working/train_set.csv', index=False)
df_test.to_csv('/kaggle/working/test_set.csv', index=False)